services:
  opencv:
    image: clauboard/opencv-cuda:latest
    container_name: ${PROJECT_NAME}-opencv
    volumes:
      - ../src:/workspace/src
    working_dir: /workspace/src
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]