services:
  msp430:
    image: cdelledonne/msp430-gcc:latest
    container_name: ${PROJECT_NAME}-msp430
    devices:
      - ${DEVICE}:${DEVICE}
    volumes:
      - ../src:/workspace/src
    working_dir: /workspace/src
    stdin_open: true
    tty: true