server {
    listen 80;
    server_name grafana.localhost;

    resolver 127.0.0.11 valid=10s;

    location / {
        set $upstream clauboard-grafana:3000;
        proxy_pass http://$upstream;
        proxy_set_header Host $host;
    }
}