server {
    listen 80;
    server_name influxdb.localhost;

    resolver 127.0.0.11 valid=10s;

    location / {
        set $upstream clauboard-influxdb:8086;
        proxy_pass http://$upstream;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}