server {
    listen 80;
    server_name <id-de-la-app>.localhost;

    resolver 127.0.0.11 valid=10s;

    location / {
        set $upstream <container_name>:<puerto interno>;
        proxy_pass http://$upstream;
        proxy_set_header Host $host;
    }
}