services:
  rpi-pico:
    image: ${MICRO_IMAGE}
    container_name: ${PROJECT_NAME}-rpi-pico
    devices:
      - ${DEVICE}:${DEVICE}
    volumes:
      - ../src:/workspace/src
    working_dir: /workspace/src
    stdin_open: true
    tty: true