services:
  stm32:
    image: ${MICRO_IMAGE}
    container_name: ${PROJECT_NAME}-stm32
    privileged: true
    ports:
      # Puerto de  OpenOCD para el GDB remoro.
      - "3333:3333"
      # Puerto de telnet de OpenOCD
      - "4444:4444"
    volumes:
      - ../src:/workspace/src
    working_dir: /workspace/src
    stdin_open: true
    tty: true